### PR TITLE
Install epel-release repo on centos/redhat

### PR DESCRIPTION
**Pull request by andreagrax**
I've added this step to add the epel repo on centos/redhat

### CODE REVIEW

**Comment by sourcejedi** [comment]
Thanks for your report!

AFAICT this should use `package` module instead of `yum` module, to allow for when/if they upgrade from `yum` to `dnf`.

I like the idea of supporting it.  But I feel like I should be mentioning that we enable EPEL, in the README for this role.  Presumably some people don't like to enable EPEL.  If you add a sentence under **Requirements**, I will be able to merge this.

Which specific version number of Enterprise Linux did you test on btw?  Apologies for listing CentOS as supported.  I don't actually use it anywhere.

**Comment by sourcejedi** [comment]
You could also update the sentence "Used sucessfully on Fedora, Debian, and Ubuntu 16.04+".  If you're happily using it on CentOS, it could be nice to add that to the list.

**Comment by andreagrax** [comment]
Hello Alan, 
I've updated the README and forced the installation of the EPEL repo only under CentOS , so no further testing needed for RHEL

**Comment by andreagrax** [comment]
Also changed from yum to package , to be more backend-agnostic

**Comment by sourcejedi** [comment]
Merged with thanks.  It makes me happy to see someone looked at the role(s) I published :).

**Pull request merged**
